apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: nfs-volume