# Storage class using azure disk
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-disk
parameters:
  kind: managed
  storageaccounttype: StandardSSD_LRS
provisioner: kubernetes.io/azure-disk