#kubectl create secret tls tls-secret-name --cert=cert.crt --key=cert.key

apiVersion: v1
kind: secret
metadata:
  creationTimestamp: null
  name: tls-secret-name
type: kubernetes.io/tls
data:
  tls.crt: <base64 encoded cert>
  tls.key: <base64 encoded key>