apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: "2023-07-26T07:37:02Z"
  name: blue-role-cka21-arch
  resourceVersion: "2678"
  uid: ed3a5e04-3979-4293-a2cd-031f73a608fd
rules:
- apiGroups:
  - apps
  resources:
  - pods
  verbs:
  - get