apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: message-queue
    component: consumer
    chapter: jobs
  name: consumer
spec:
  parallelism: 5
  template:
    metadata:
      labels:
        app: message-queue
        component: consumer
        chapter: jobs
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: worker
        imagePullPolicy: Always
        command:
        - /kuard
        args:
        - --keygen-enable
        - --keygen-exit-on-complete
        - --keygen-memq-server=http://queue:8080/memq/server
        - --keygen-memq-queue=keygen
      restartPolicy: OnFailure
