apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
spec:
  containers:
    - name: pod-affinity-container
      image: nginx
  affinity:
    podAntiAffinity:
      #requiredDuringSchedulingIgnoredDuringExecution is a hard requirement.
      requiredDuringSchedulingIgnoredDuringExecution: #Use preferredDuringSchedulingIgnoredDuringExecution for a soft requirement
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - affinityName
          topologyKey: "kubernetes.io/hostname"