apiVersion: v1
kind: Pod
metadata:
  name: pod-affinity
spec:
  containers:
    - name: pod-affinity-container
      image: nginx
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - affinityName
          topologyKey: "kubernetes.io/hostname"