apiVersion: v1
kind: Pod
metadata:
  name: pod-using-serviceaccount
  namespace: default
containers:
  - name: pod-using-serviceaccount
    image: nginx
    ports:
      - containerPort: 80
    spec:
      serviceAccountName: service-account