# External endpoints using an IP address
apiVersion: v1
kind: Endpoints
metadata:
  name: external-ip-database
subsets:
  - addresses:
      - ip: 192.168.1.1
    ports:
      - port: 3306
        name: mysql